variable "aws_region" {}
variable "environment" {}
variable "vpc_cidr_block" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "db_subnet_cidr" {}
variable "public_source_gateway_cidr_block" {}
variable "private_source_gateway_cidr_block" {}
variable "database_username" {}
variable "database_password" {}
variable "database_name" {}