pipeline{
    agent any
    environment{
        AWS_CRED=credentials('AWS_CRED_ID')
    }
    stages{
        stage('Git Checkout'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sriram-ravi705/2-tier-app-deployment.git']])
            }
        }
        stage('Terraform init'){
            steps{
                sh 'terraform init'
            }
        }
        stage('Terraform plan'){
            steps{
                sh "terraform plan -var-file='environments/test.tfvars'"
            }
        }
        stage('Terraform apply'){
            steps{
                sh'''
                terraform apply -var-file='environments/test.tfvars' -auto-approve
                terraform apply --target="module.public_ec2" -var-file='environments/test.tfvars' -auto-approve
                '''
            }
        }
    }
}